---
name: Práctica Hechos y Reglas
locale: es
type: practice
beta: false
teacher_info: 
language: prolog
id_format: '%05d'
order:
- 1
- 10
- 20
- 2
- 30
- 40
- 3
- 4
- 60
- 5
- 50
- 6
- 7
- 70
- 71
- 72
